services:
  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__TodoDb=Host=postgresql;Database=tododb;Username=todouser;Password=102030
      - TokenSettings__SecretKey=d7a1d34ffe3c44cf2056a0a6bbad31f3c5ec28b1510a3995b4cb2dc4fb3d670a
      - TokenSettings__ExpirationTimeInHours=2
      - EmailSettings__FromAddress=
      - EmailSettings__SmtpServer=
      - EmailSettings__SmtpPort=
      - EmailSettings__SmtpUser=
      - EmailSettings__SmtpPassword=
    networks:
      - todo-network
  
  app:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    environment:
      - API_URL=http://localhost:8080
    ports:
      - "3000:3000"
    networks:
      - todo-network

  postgresql:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=todouser
      - POSTGRES_DB=tododb
      - POSTGRES_PASSWORD=102030
    restart: always
    networks:
      - todo-network


volumes:
  postgresql_data:
    driver: local

networks:
  todo-network:
    driver: bridge